# Generated by Django 5.1.6 on 2025-03-01 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trade", "0002_orderhistory_delete_transactionstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderHistory",
        ),
    ]
