# Generated by Django 5.1.6 on 2025-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='method',
        ),
        migrations.AddField(
            model_name='spottrade',
            name='fee_symbol',
            field=models.CharField(default='twd', max_length=10),
        ),
        migrations.AddField(
            model_name='spottrade',
            name='user_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='fee_symbol',
            field=models.CharField(default='twd', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='user_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='fee',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='open_position',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='profit',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='sold_price',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spottrade',
            name='target_after_exceed',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fee',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
