# Generated by Django 5.1.6 on 2025-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_remove_trade_method_spottrade_fee_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='fee',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
