# Generated by Django 5.1.6 on 2025-05-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_trade_fee_alter_trade_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='fee_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
